env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  camelcase: 0
  import/no-extraneous-dependencies: 0
  max-classes-per-file: 0
  max-len: [2, { code: 160, ignoreComments: true, ignoreTemplateLiterals: true, ignoreUrls: true }]
  no-console: 0
  object-curly-newline: [2, { ObjectPattern: { multiline: true } }]
