# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
printWidth: 120
overrides:
  - files: "*.sol"
    options:
      singleQuote: false
      tabWidth: 4
  - files: "*.yaml"
    options:
      singleQuote: false
